### ISSUE TITLE
Queuing on QlikView

### ISSUE THREAD

**Issue by steveonabike** [eapowertools/QlikSenseTask#26]
This is a great tool. We use it all the time. One thing we're trying to overcome is queuing on the QlikView QMC for these Qlik Sense tasks. Since they take so little QlikView resources to run, we're curious to see how we can eliminate queuing.

**Comment by marcusspitzmiller** [comment]
Hi, i'm glad you like it.  Not sure i follow though.  If you omit -wait, the program will return immediately without checking for an error code, else if you specific a -wait, it will then of course wait.

Otherwise if you are talking about the QlikView side queuing and not actually running as many tasks as you would like, then you need to look at the maximum number of concurrent tasks Publisher is set to be able to run.
